### ISSUE TITLE
IE8 下会报 File 未定义

### ISSUE THREAD

**Issue by sunbinbin007** [musicode/soga#1]
![DINGTALK_IM_3487500464](https://user-images.githubusercontent.com/13409926/68013134-1dca4f00-fcc7-11e9-8e13-760361a52048.JPG)

**Comment by musicode** [comment]
忘了判断 File 了，我的错，等下发个新版

**Comment by musicode** [comment]
soga@0.1.8 已发布

**Comment by musicode** [comment]
路由又更新了一版，发现了更好的解决方式

**Comment by sunbinbin007** [comment]
好的

**Comment by musicode** [comment]
@DengXiaChen 你这是碰到了啥需要支持 IE8 的项目了吗？
